spring:
  datasource:
    username: ${app.dbUsername:root}
    password: ${app.dbPassword:123456}
    url: jdbc:mysql://${app.dbHost:127.0.0.1}:3306/sharding?useUnicode=true&characterEncoding=utf-8&useSSL=false